---
- hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copying the jar file
      copy:
        src: /var/lib/jenkins/workspace/petclinic/target/spring-petclinic-2.2.0.jar
        dest: /usr/share/tomcat/webapps/spring-petclinic-2.2.0.jar
   # - name: Coptying the sh file
    #  copy:
     #   src: newdeploy.sh
      #  dest: /root/newdeploy.sh
       # mode: 0777
    #- name: Deployment
     # command: sh /root/newdeploy.sh
