---
- hosts: all
  remote_user: root
  tasks:
    - name: Coptying the jar file
      copy:
        src: /var/lib/jenkins/workspace/spring-petclinic_master/target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
        dest: /root/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
    - name: Coptying the sh file
      copy:
        src: newdeploy.sh
        dest: /root/newdeploy.sh
        mode: 0777
    - name: Deployment
      command: sh /root/newdeploy.sh
